[app]
# 业务配置
app = "sgame_1v1"
self_play = true
set_name = "set1"
self_play_set_name = "set1"
selfplay_app_conf = "conf/app_conf_sgame1v1_selfplay.json"
noselfplay_app_conf = "conf/app_conf_sgame1v1_noselfplay.json"
algo_conf = "conf/algo_conf_sgame1v1.json"

# learner训练批处理大小限制
train_batch_size = 512

# 样本消耗/生成采样比
production_consume_ratio = 1

# 超参数
learning_rate = 2e-5
# entropy_loss_weight
var_beta = 0.1
ppo_clip_range = 0.2

# 下面是日志文件相关配置
log_dir = "/data/projects/1v1/log"
level = "INFO"
tensorflow_log_level = "INFO"

# 采用的算法
algo = "ppo"

# actor预测批处理大小
predict_batch_size = 32

# aisrv在单局里多次发送样本大小配置
send_sample_size = 100000

# 下面是replay buffer的相关配置
replay_buffer_capacity = 40960
preload_ratio = 10

# 如果采用特征值处理的库是其他的插件, 则需要配置下, 否则忽略该配置项
feature_process_lib_interface_configure = "/data/projects/1v1/environment/feature_process/config.dat"


eval_model_dir = '/data/projects/1v1/ckpt/model.ckpt-191231'
